% define fixed resonator and sweep parameters
Q0=10000; f0=1e9; n=1001; rel_span=10;

% define coupling range
    % maximum
    bmax=100;
    % number of decades to test
    ndec=5;
    % number of poits per decade
    ppd=3;
    % divider
    div=10^(1/ppd);
    % lower coupling limit (not to be reached)
    blim=bmax/(div)^(ppd*ndec+0.5);


% inicialize coupling factor port 1
b1=bmax; 

% inicialize index n1
n1=1; 

while b1>blim
    b2=b1;
    n2=1;
    while b2>blim
        % Generate S-parameters
         [S11,S12,S21,S22,f] = res_s_par(b1,b2,Q0,f0,n,rel_span);
      
        % File name
            %filename = 'output.s2p';
            filename = sprintf('output_%d_%d.s2p', n1, n2);

        
        % Open file for writing
            fid = fopen(filename, 'w');
            if fid == -1
                error('Cannot open file for writing.');
            end
        
        % Write Touchstone header
            %fprintf(fid, '! Touchstone file generated by MATLAB\n');
            fprintf(fid, '! File generated for n1 = %d, n2 = %d\n', n1, n2);
            fprintf(fid, '! b1 = %.6f\n', b1);
            fprintf(fid, '! b2 = %.6f\n', b2);
            fprintf(fid, '! Q0 = %.6f\n', Q0);
            fprintf(fid, '! f0 = %.6f\n', f0);
            fprintf(fid, '! n = %d\n', n);
            fprintf(fid, '! rel_span = %.6f\n', rel_span);
            fprintf(fid, '# Hz S RI R 50\n');
        
        % Loop through each frequency point and write S-parameters
            for k = 1:length(f)
                fprintf(fid, '%.20e ', f(k));  % frequency
                fprintf(fid, '%.20e %.20e ', real(S11(k)), imag(S11(k)));
                fprintf(fid, '%.20e %.20e ', real(S21(k)), imag(S21(k)));
                fprintf(fid, '%.20e %.20e ', real(S12(k)), imag(S12(k)));
                fprintf(fid, '%.20e %.20e\n', real(S22(k)), imag(S22(k)));
            end
        
        % Close the file
            fclose(fid);
        
        disp(['S2P file written to ', filename]);
        b2=b2/div;
        n2=n2+1;
    end
    b1=b1/div;
    n1=n1+1;
end
