
% Generate S-parameters
    b1=1.5; b2=0.2; Q0=10000; f0=1e9; n=401; rel_span=5;
    [S11,S12,S21,S22,f] = res_s_par(b1,b2,Q0,f0,n,rel_span);

% File name
filename = 'output.s2p';

% Open file for writing
fid = fopen(filename, 'w');
if fid == -1
    error('Cannot open file for writing.');
end

% Write Touchstone header
fprintf(fid, '! Touchstone file generated by MATLAB\n');
fprintf(fid, '! b1 = %.6f\n', b1);
fprintf(fid, '! b2 = %.6f\n', b2);
fprintf(fid, '! Q0 = %.6f\n', Q0);
fprintf(fid, '! f0 = %.6f\n', f0);
fprintf(fid, '! n = %d\n', n);
fprintf(fid, '! rel_span = %.6f\n', rel_span);
fprintf(fid, '# Hz S RI R 50\n');

% Loop through each frequency point and write S-parameters
for k = 1:length(f)
    fprintf(fid, '%.20e ', f(k));  % frequency
    fprintf(fid, '%.20e %.20e ', real(S11(k)), imag(S11(k)));
    fprintf(fid, '%.20e %.20e ', real(S21(k)), imag(S21(k)));
    fprintf(fid, '%.20e %.20e ', real(S12(k)), imag(S12(k)));
    fprintf(fid, '%.20e %.20e\n', real(S22(k)), imag(S22(k)));
end

% Close the file
fclose(fid);

disp(['S2P file written to ', filename]);
