name: Docker Image CI

on:
  push:
    branches: [ "main", "prod", "qa" ]
  pull_request:
    branches: []
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dockerregistry.arpe.customers.herolditservice.de/arpe:$(github.sha)
    - name: Login to Docker Registry
      run: echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_REGISTRY_USERNAME }}" --password-stdin
    - name: Push the Docker image
      run: docker push dockerregistry.arpe.customers.herolditservice.de/arpe:$(github.sha)
      
